import { awlCards } from "./awl.generated";

export type Rating = "forgot" | "hard" | "remembered";
export type WordCard = { id:number; word:string; phonetic:string; type:string; meaning:string; note:string; family:string[]; example:string; exampleVi:string; topic:string };

const featuredCards: WordCard[] = [
  { id:1, word:"analyse", phonetic:"/ˈænəlaɪz/", type:"verb", meaning:"phân tích", note:"Xem xét kỹ để hiểu bản chất hoặc mối quan hệ giữa các phần.", family:["analysis (n)","analyst (n)","analytical (adj)"], example:"Researchers analysed the data before drawing a conclusion.", exampleVi:"Các nhà nghiên cứu đã phân tích dữ liệu trước khi đưa ra kết luận.", topic:"Nghiên cứu" },
  { id:2, word:"assess", phonetic:"/əˈses/", type:"verb", meaning:"đánh giá", note:"Đưa ra nhận định về chất lượng, mức độ hoặc giá trị.", family:["assessment (n)","assessor (n)"], example:"Schools should assess students through a range of activities.", exampleVi:"Trường học nên đánh giá học sinh thông qua nhiều hoạt động.", topic:"Giáo dục" },
  { id:3, word:"sustain", phonetic:"/səˈsteɪn/", type:"verb", meaning:"duy trì; chống đỡ", note:"Giữ cho một quá trình tiếp tục trong thời gian dài.", family:["sustainable (adj)","sustainability (n)"], example:"Cities need sustainable solutions to reduce air pollution.", exampleVi:"Các thành phố cần giải pháp bền vững để giảm ô nhiễm không khí.", topic:"Môi trường" },
  { id:4, word:"significant", phonetic:"/sɪɡˈnɪfɪkənt/", type:"adjective", meaning:"đáng kể; quan trọng", note:"Đủ lớn hoặc quan trọng để được chú ý.", family:["significance (n)","significantly (adv)"], example:"There was a significant increase in online learning.", exampleVi:"Đã có sự gia tăng đáng kể trong việc học trực tuyến.", topic:"Giáo dục" },
  { id:5, word:"derive", phonetic:"/dɪˈraɪv/", type:"verb", meaning:"bắt nguồn; suy ra", note:"Nhận được hoặc phát triển từ một nguồn cụ thể.", family:["derivation (n)","derivative (adj/n)"], example:"Many medicines are derived from natural substances.", exampleVi:"Nhiều loại thuốc có nguồn gốc từ các chất tự nhiên.", topic:"Nghiên cứu" },
  { id:6, word:"implement", phonetic:"/ˈɪmplɪment/", type:"verb", meaning:"thực hiện; triển khai", note:"Đưa một kế hoạch hoặc chính sách vào thực tế.", family:["implementation (n)"], example:"The government implemented a new recycling policy.", exampleVi:"Chính phủ đã triển khai một chính sách tái chế mới.", topic:"Xã hội" },
  { id:7, word:"allocate", phonetic:"/ˈæləkeɪt/", type:"verb", meaning:"phân bổ", note:"Chia nguồn lực cho một mục đích cụ thể.", family:["allocation (n)"], example:"More funding should be allocated to public transport.", exampleVi:"Nên phân bổ thêm ngân sách cho giao thông công cộng.", topic:"Kinh tế" },
  { id:8, word:"innovate", phonetic:"/ˈɪnəveɪt/", type:"verb", meaning:"đổi mới; sáng tạo", note:"Giới thiệu ý tưởng hoặc phương pháp mới.", family:["innovation (n)","innovative (adj)","innovator (n)"], example:"Companies must innovate to remain competitive.", exampleVi:"Các công ty phải đổi mới để duy trì khả năng cạnh tranh.", topic:"Công nghệ" },
  { id:9, word:"evaluate", phonetic:"/ɪˈvæljueɪt/", type:"verb", meaning:"đánh giá, thẩm định", note:"Xem xét thông tin để quyết định mức độ hiệu quả.", family:["evaluation (n)","evaluative (adj)"], example:"The study evaluates the impact of social media on teenagers.", exampleVi:"Nghiên cứu đánh giá tác động của mạng xã hội lên thanh thiếu niên.", topic:"Nghiên cứu" },
  { id:10, word:"contribute", phonetic:"/kənˈtrɪbjuːt/", type:"verb", meaning:"đóng góp; góp phần", note:"Giúp tạo nên một kết quả chung.", family:["contribution (n)","contributor (n)"], example:"Vehicle emissions contribute to climate change.", exampleVi:"Khí thải xe cộ góp phần gây ra biến đổi khí hậu.", topic:"Môi trường" },
  { id:11, word:"infrastructure", phonetic:"/ˈɪnfrəstrʌktʃə/", type:"noun", meaning:"cơ sở hạ tầng", note:"Các hệ thống cơ bản cần thiết để xã hội vận hành.", family:["infrastructural (adj)"], example:"Reliable digital infrastructure supports remote education.", exampleVi:"Hạ tầng số đáng tin cậy hỗ trợ giáo dục từ xa.", topic:"Công nghệ" },
  { id:12, word:"regulate", phonetic:"/ˈreɡjuleɪt/", type:"verb", meaning:"điều chỉnh; quản lý", note:"Kiểm soát bằng quy tắc hoặc luật lệ.", family:["regulation (n)","regulatory (adj)","regulator (n)"], example:"Governments should regulate the use of personal data.", exampleVi:"Chính phủ nên quản lý việc sử dụng dữ liệu cá nhân.", topic:"Xã hội" },
  { id:13, word:"fluctuate", phonetic:"/ˈflʌktʃueɪt/", type:"verb", meaning:"dao động", note:"Tăng giảm không ổn định theo thời gian.", family:["fluctuation (n)"], example:"Oil prices fluctuated considerably during the period.", exampleVi:"Giá dầu dao động đáng kể trong giai đoạn này.", topic:"Kinh tế" },
  { id:14, word:"hypothesis", phonetic:"/haɪˈpɒθəsɪs/", type:"noun", meaning:"giả thuyết", note:"Lời giải thích tạm thời cần được kiểm chứng.", family:["hypotheses (pl)","hypothesise (v)","hypothetical (adj)"], example:"The results did not support the original hypothesis.", exampleVi:"Kết quả không ủng hộ giả thuyết ban đầu.", topic:"Nghiên cứu" },
  { id:15, word:"facilitate", phonetic:"/fəˈsɪlɪteɪt/", type:"verb", meaning:"tạo điều kiện", note:"Làm cho một hành động hoặc quá trình dễ dàng hơn.", family:["facilitation (n)","facilitator (n)"], example:"Technology can facilitate collaboration between students.", exampleVi:"Công nghệ có thể tạo điều kiện cho học sinh hợp tác.", topic:"Giáo dục" },
  { id:16, word:"diminish", phonetic:"/dɪˈmɪnɪʃ/", type:"verb", meaning:"giảm bớt; suy giảm", note:"Trở nên hoặc làm cho nhỏ hơn, yếu hơn.", family:["diminished (adj)","diminution (n)"], example:"Natural resources are diminishing at an alarming rate.", exampleVi:"Tài nguyên thiên nhiên đang suy giảm với tốc độ đáng báo động.", topic:"Môi trường" },
  { id:17, word:"revenue", phonetic:"/ˈrevənjuː/", type:"noun", meaning:"doanh thu; nguồn thu", note:"Tổng tiền một tổ chức hoặc chính phủ nhận được.", family:["revenue (uncountable/countable)"], example:"Tourism generates substantial revenue for the region.", exampleVi:"Du lịch tạo ra nguồn thu đáng kể cho khu vực.", topic:"Kinh tế" },
  { id:18, word:"automate", phonetic:"/ˈɔːtəmeɪt/", type:"verb", meaning:"tự động hóa", note:"Dùng máy móc hoặc phần mềm để vận hành tự động.", family:["automation (n)","automated (adj)","automatic (adj)"], example:"Many routine tasks can now be automated.", exampleVi:"Nhiều tác vụ thường lệ hiện có thể được tự động hóa.", topic:"Công nghệ" },
];

const featuredByWord = new Map(featuredCards.map((card) => [card.word, card]));

export const cards: WordCard[] = awlCards.map((card) => {
  const featured = featuredByWord.get(card.word);
  return featured ? { ...card, ...featured, id: card.id, topic: card.topic } : card;
});
